export type Category = 'editorial' | 'heritage' | 'senator' | 'evening' | 'pieces' | 'details' | 'studio';
export type Stage = 'measure' | 'cut' | 'sew' | 'fit' | 'ready';
export type Work = { src: string; w: number; h: number; alt: string; cat: Category; stage?: Stage };

export const works: Work[] = [
  // editorial (27)
  { src: '/images/work/ts-29.webp', w: 864, h: 1080, alt: "Two looks in green and black and mustard Ankara", cat: 'editorial' },
  { src: '/images/work/ts-30.webp', w: 2000, h: 2501, alt: "Kente print two piece with saxophone", cat: 'editorial' },
  { src: '/images/work/ts-31.webp', w: 2000, h: 2500, alt: "Kente set with a burgundy beret", cat: 'editorial' },
  { src: '/images/work/ts-32.webp', w: 2000, h: 2500, alt: "Kente look styled with a leather pouf", cat: 'editorial' },
  { src: '/images/work/ts-33.webp', w: 2000, h: 2501, alt: "Kente set in motion with a saxophone", cat: 'editorial' },
  { src: '/images/work/ts-34.webp', w: 2000, h: 2500, alt: "Kente look seated on the stone ledge", cat: 'editorial' },
  { src: '/images/work/ts-35.webp', w: 2000, h: 2500, alt: "White mesh tank and wide trousers on a yellow chair", cat: 'editorial' },
  { src: '/images/work/ts-36.webp', w: 2000, h: 2500, alt: "All white relaxed look in the showroom", cat: 'editorial' },
  { src: '/images/work/ts-37.webp', w: 2000, h: 2500, alt: "Close portrait in a white mesh top and pearls", cat: 'editorial' },
  { src: '/images/work/ts-38.webp', w: 2000, h: 2500, alt: "White mesh set against the brick wall", cat: 'editorial' },
  { src: '/images/work/ts-39.webp', w: 2000, h: 2500, alt: "Two printed shirt and trouser sets in brown and coral", cat: 'editorial' },
  { src: '/images/work/ts-40.webp', w: 2000, h: 2500, alt: "Brown and coral printed sets between the clothing rails", cat: 'editorial' },
  { src: '/images/work/ts-41.webp', w: 2000, h: 2500, alt: "Coral print set reaching for the rail", cat: 'editorial' },
  { src: '/images/work/ts-42.webp', w: 1306, h: 1959, alt: "Brown printed set close portrait", cat: 'editorial' },
  { src: '/images/work/ts-43.webp', w: 2000, h: 2500, alt: "Brown print set walking through the showroom", cat: 'editorial' },
  { src: '/images/work/ts-44.webp', w: 2000, h: 2500, alt: "Coral print set with a red cap", cat: 'editorial' },
  { src: '/images/work/ts-45.webp', w: 2000, h: 2500, alt: "Coral and brown print looks by the rails", cat: 'editorial' },
  { src: '/images/work/ts-46.webp', w: 2000, h: 2500, alt: "Coral print set adjusting a hanger", cat: 'editorial' },
  { src: '/images/work/ts-47.webp', w: 2000, h: 2500, alt: "Coral print set with cowrie cap", cat: 'editorial' },
  { src: '/images/work/ts-48.webp', w: 2000, h: 2500, alt: "Coral print set at the fabric rail", cat: 'editorial' },
  { src: '/images/work/ts-49.webp', w: 2000, h: 2500, alt: "Red cowrie cap detail", cat: 'editorial' },
  { src: '/images/work/ts-51.webp', w: 2000, h: 2501, alt: "Green printed set seated by cognac chairs", cat: 'editorial' },
  { src: '/images/work/ts-52.webp', w: 2000, h: 2500, alt: "Green set and mustard and black set under the logo", cat: 'editorial' },
  { src: '/images/work/ts-53.webp', w: 2000, h: 2500, alt: "Two printed looks under the Tatiana logo", cat: 'editorial' },
  { src: '/images/work/ts-54.webp', w: 2000, h: 2500, alt: "Green and mustard looks side by side", cat: 'editorial' },
  { src: '/images/work/ts-55.webp', w: 2000, h: 2501, alt: "Green and mustard looks seated together", cat: 'editorial' },
  { src: '/images/work/ts-96.webp', w: 1400, h: 1750, alt: "Black and white print set in the showroom", cat: 'editorial' },
  // heritage (22)
  { src: '/images/work/ts-09.webp', w: 994, h: 1280, alt: "Chief in a cream and red ceremonial outfit with coral beads", cat: 'heritage' },
  { src: '/images/work/ts-11.webp', w: 962, h: 1280, alt: "Two clients in red heritage prints beside a white truck", cat: 'heritage' },
  { src: '/images/work/ts-12.webp', w: 1026, h: 1280, alt: "Matching red heritage outfits for a traditional outing", cat: 'heritage' },
  { src: '/images/work/ts-15.webp', w: 982, h: 1280, alt: "Celebrant in cream isiagu with red sash and hand fan", cat: 'heritage' },
  { src: '/images/work/ts-16.webp', w: 962, h: 1280, alt: "Red and cream ceremonial look at an evening party", cat: 'heritage' },
  { src: '/images/work/ts-18.webp', w: 996, h: 1280, alt: "Ceremonial look on the dance floor", cat: 'heritage' },
  { src: '/images/work/ts-56.webp', w: 1024, h: 1280, alt: "Grey wrapper and shirt with a beaded hand fan", cat: 'heritage' },
  { src: '/images/work/ts-57.webp', w: 1024, h: 1280, alt: "Red print isiagu style set with hand fan", cat: 'heritage' },
  { src: '/images/work/ts-58.webp', w: 1024, h: 1280, alt: "Red print set with chieftaincy fan beside a truck", cat: 'heritage' },
  { src: '/images/work/ts-60.webp', w: 826, h: 1080, alt: "Client in white lace with a red cap", cat: 'heritage' },
  { src: '/images/work/ts-63.webp', w: 960, h: 1280, alt: "Black kaftan with layered coral beads", cat: 'heritage' },
  { src: '/images/work/ts-64.webp', w: 1028, h: 1280, alt: "Black ceremonial kaftan with hand fan", cat: 'heritage' },
  { src: '/images/work/ts-65.webp', w: 1024, h: 1280, alt: "Red print set, full length", cat: 'heritage' },
  { src: '/images/work/ts-68.webp', w: 1028, h: 1280, alt: "Black kaftans and red caps at a family gathering", cat: 'heritage' },
  { src: '/images/work/ts-69.webp', w: 960, h: 1280, alt: "Black kaftan with red caps against red brick", cat: 'heritage' },
  { src: '/images/work/ts-70.webp', w: 1028, h: 1280, alt: "Elder and client in black with red caps", cat: 'heritage' },
  { src: '/images/work/ts-72.webp', w: 1024, h: 1280, alt: "Red print set with coral beads by a truck", cat: 'heritage' },
  { src: '/images/work/ts-73.webp', w: 742, h: 1080, alt: "White lace agbada with a Good Life hand fan", cat: 'heritage' },
  { src: '/images/work/ts-74.webp', w: 720, h: 1080, alt: "Couple in white lace at a traditional wedding", cat: 'heritage' },
  { src: '/images/work/ts-78.webp', w: 1024, h: 1280, alt: "Black kaftan with coral beads", cat: 'heritage' },
  { src: '/images/work/ts-94.webp', w: 1400, h: 1750, alt: "Red and orange striped agbada with a white cap", cat: 'heritage' },
  { src: '/images/work/ts-95.webp', w: 1400, h: 1750, alt: "Striped agbada portrait with a hand fan", cat: 'heritage' },
  // senator (22)
  { src: '/images/work/ts-00.webp', w: 956, h: 1280, alt: "Client in a stone senator outfit inside the Tatiana Stitches showroom", cat: 'senator' },
  { src: '/images/work/ts-03.webp', w: 1032, h: 1280, alt: "Client in a sky blue senator with gold neckline trim", cat: 'senator' },
  { src: '/images/work/ts-13.webp', w: 988, h: 1280, alt: "Groom and groomsmen in crisp white senators", cat: 'senator' },
  { src: '/images/work/ts-14.webp', w: 1014, h: 1280, alt: "Wedding party in white with red caps", cat: 'senator' },
  { src: '/images/work/ts-17.webp', w: 1034, h: 1280, alt: "Client seated in an off white senator", cat: 'senator' },
  { src: '/images/work/ts-19.webp', w: 1002, h: 1280, alt: "Black senator with red cap against the logo wall", cat: 'senator' },
  { src: '/images/work/ts-20.webp', w: 962, h: 1280, alt: "Off white senator with a red cap", cat: 'senator' },
  { src: '/images/work/ts-21.webp', w: 958, h: 1280, alt: "Sand coloured senator with black piping", cat: 'senator' },
  { src: '/images/work/ts-22.webp', w: 940, h: 1280, alt: "Sand senator shown full length", cat: 'senator' },
  { src: '/images/work/ts-23.webp', w: 1012, h: 1280, alt: "Charcoal senator with gold watch", cat: 'senator' },
  { src: '/images/work/ts-24.webp', w: 1010, h: 1280, alt: "Black senator worn with a gold cane and pearls", cat: 'senator' },
  { src: '/images/work/ts-25.webp', w: 934, h: 1280, alt: "Navy senator set in the studio", cat: 'senator' },
  { src: '/images/work/ts-26.webp', w: 1024, h: 1280, alt: "Black short sleeve senator styled with a cane", cat: 'senator' },
  { src: '/images/work/ts-27.webp', w: 964, h: 1280, alt: "Red agbada with white embroidery on a concert stage", cat: 'senator' },
  { src: '/images/work/ts-28.webp', w: 942, h: 1280, alt: "Charcoal senator in the studio", cat: 'senator' },
  { src: '/images/work/ts-59.webp', w: 960, h: 1280, alt: "Team in matching navy and white print shirts", cat: 'senator' },
  { src: '/images/work/ts-67.webp', w: 960, h: 1280, alt: "Navy print shirt in a relaxed lounge", cat: 'senator' },
  { src: '/images/work/ts-75.webp', w: 960, h: 1280, alt: "Navy print set in a garden lounge", cat: 'senator' },
  { src: '/images/work/ts-76.webp', w: 960, h: 1280, alt: "Navy print shirt beside a red sports car", cat: 'senator' },
  { src: '/images/work/ts-86.webp', w: 1032, h: 1280, alt: "Father and son in matching outfits", cat: 'senator' },
  { src: '/images/work/ts-92.webp', w: 1400, h: 1750, alt: "Orange print shirt and black trousers with a hand fan", cat: 'senator' },
  { src: '/images/work/ts-93.webp', w: 1400, h: 1750, alt: "Print shirt look seated in the studio", cat: 'senator' },
  // evening (8)
  { src: '/images/work/ts-62.webp', w: 720, h: 1080, alt: "Black silk shirt and trousers on a sand backdrop", cat: 'evening' },
  { src: '/images/work/ts-66.webp', w: 720, h: 1080, alt: "Two looks in black silk, seated", cat: 'evening' },
  { src: '/images/work/ts-71.webp', w: 720, h: 1080, alt: "Two looks in black silk, standing", cat: 'evening' },
  { src: '/images/work/ts-77.webp', w: 720, h: 1080, alt: "Black silk shirt portrait", cat: 'evening' },
  { src: '/images/work/ts-88.webp', w: 1400, h: 1750, alt: "Pale grey double breasted suit with floral embroidery", cat: 'evening' },
  { src: '/images/work/ts-89.webp', w: 1400, h: 1750, alt: "Grey embroidered suit against the stone wall", cat: 'evening' },
  { src: '/images/work/ts-90.webp', w: 1400, h: 1750, alt: "Black blazer worn with a burgundy fedora", cat: 'evening' },
  { src: '/images/work/ts-91.webp', w: 1400, h: 1749, alt: "Black blazer over a black tee", cat: 'evening' },
  // pieces (20)
  { src: '/images/work/ts-01.webp', w: 974, h: 1280, alt: "White lace agbada on a mannequin against the stone wall", cat: 'pieces' },
  { src: '/images/work/ts-02.webp', w: 1010, h: 1280, alt: "Close look at a wine red tunic with cowrie sleeve detail", cat: 'pieces' },
  { src: '/images/work/ts-04.webp', w: 982, h: 1280, alt: "Wine red isiagu style tunic with beaded hem on a mannequin", cat: 'pieces' },
  { src: '/images/work/ts-06.webp', w: 988, h: 1280, alt: "Wine red tunic styled with coral beads on a mannequin", cat: 'pieces' },
  { src: '/images/work/ts-10.webp', w: 1024, h: 1280, alt: "Green kaftan set in the studio", cat: 'pieces' },
  { src: '/images/work/ts-97.webp', w: 1400, h: 1750, alt: "White senator on a mannequin with a woven cap", cat: 'pieces' },
  { src: '/images/work/ts-98.webp', w: 1400, h: 1750, alt: "White senator set shown full length", cat: 'pieces' },
  { src: '/images/work/ts-99.webp', w: 713, h: 713, alt: "Wine tunic with a white applique on a gold mannequin", cat: 'pieces' },
  { src: '/images/work/ts-100.webp', w: 720, h: 739, alt: "Royal blue agbada with tonal embroidery", cat: 'pieces' },
  { src: '/images/work/ts-101.webp', w: 1350, h: 1687, alt: "Blue agbada with a checked embroidered chest", cat: 'pieces' },
  { src: '/images/work/ts-102.webp', w: 720, h: 720, alt: "Purple tunic with a white damask panel", cat: 'pieces' },
  { src: '/images/work/ts-103.webp', w: 720, h: 720, alt: "Black pinstripe short sleeve senator", cat: 'pieces' },
  { src: '/images/work/ts-104.webp', w: 1400, h: 1746, alt: "Mustard agbada with a ribbed chest panel", cat: 'pieces' },
  { src: '/images/work/ts-105.webp', w: 1400, h: 1750, alt: "Mustard agbada on a black mannequin", cat: 'pieces' },
  { src: '/images/work/ts-106.webp', w: 1400, h: 1750, alt: "Blue and mustard agbadas side by side", cat: 'pieces' },
  { src: '/images/work/ts-107.webp', w: 1280, h: 1280, alt: "Teal tunic with red, blue and cream embroidery", cat: 'pieces' },
  { src: '/images/work/ts-108.webp', w: 1280, h: 1280, alt: "Close view of the teal tunic neckline", cat: 'pieces' },
  { src: '/images/work/ts-109.webp', w: 1400, h: 1400, alt: "Pink agbada with white geometric embroidery", cat: 'pieces' },
  { src: '/images/work/ts-110.webp', w: 1400, h: 1400, alt: "Pink agbada with the sleeve folded", cat: 'pieces' },
  { src: '/images/work/ts-111.webp', w: 1400, h: 1750, alt: "Black and white agbada with a pleated chest panel", cat: 'pieces' },
  // details (11)
  { src: '/images/work/ts-112.webp', w: 1400, h: 1750, alt: "Striped shirts on the rail with Tatiana labels", cat: 'details' },
  { src: '/images/work/ts-113.webp', w: 1080, h: 1337, alt: "Rail of black shirts with gold embroidery", cat: 'details' },
  { src: '/images/work/ts-114.webp', w: 1400, h: 1750, alt: "Teal sleeve with a clean turned cuff", cat: 'details' },
  { src: '/images/work/ts-115.webp', w: 1400, h: 1746, alt: "Ribbed embroidery on a mustard agbada", cat: 'details' },
  { src: '/images/work/ts-116.webp', w: 1400, h: 1750, alt: "Hand stitched shoulder on a blue agbada", cat: 'details' },
  { src: '/images/work/ts-117.webp', w: 1400, h: 1750, alt: "Blue agbada neckline with white embroidery", cat: 'details' },
  { src: '/images/work/ts-118.webp', w: 1400, h: 1746, alt: "Woven cap in gold, brown and black", cat: 'details' },
  { src: '/images/work/ts-119.webp', w: 1400, h: 1746, alt: "Patterned cap on a white mannequin", cat: 'details' },
  { src: '/images/work/ts-120.webp', w: 1400, h: 1750, alt: "Embroidered cap in black and cream", cat: 'details' },
  { src: '/images/work/ts-121.webp', w: 1400, h: 1750, alt: "Cap embroidery seen from the side", cat: 'details' },
  { src: '/images/work/ts-122.webp', w: 1400, h: 1400, alt: "Dark blue textured cap", cat: 'details' },
  // studio (15)
  { src: '/images/work/ts-82.webp', w: 720, h: 1080, alt: "Taking measurements for a white outfit", cat: 'studio', stage: 'measure' },
  { src: '/images/work/ts-87.webp', w: 720, h: 1080, alt: "Taking measurements for a white outfit", cat: 'studio', stage: 'measure' },
  { src: '/images/work/ts-85.webp', w: 810, h: 1080, alt: "Measuring a client at home", cat: 'studio', stage: 'measure' },
  { src: '/images/work/ts-123.webp', w: 494, h: 776, alt: "Marking fabric with the tape close at hand", cat: 'studio', stage: 'cut' },
  { src: '/images/work/ts-124.webp', w: 487, h: 603, alt: "Drafting a pattern on white fabric", cat: 'studio', stage: 'cut' },
  { src: '/images/work/ts-125.webp', w: 496, h: 607, alt: "Chalk lines going down before the first cut", cat: 'studio', stage: 'cut' },
  { src: '/images/work/ts-126.webp', w: 503, h: 601, alt: "Checking the lines against the measurements", cat: 'studio', stage: 'cut' },
  { src: '/images/work/ts-127.webp', w: 496, h: 788, alt: "At the sewing machine in the workroom", cat: 'studio', stage: 'sew' },
  { src: '/images/work/ts-128.webp', w: 490, h: 682, alt: "Feeding white fabric through the machine", cat: 'studio', stage: 'sew' },
  { src: '/images/work/ts-129.webp', w: 491, h: 712, alt: "Sewing a white senator", cat: 'studio', stage: 'sew' },
  { src: '/images/work/ts-130.webp', w: 493, h: 779, alt: "Stitching a black seam by hand and machine", cat: 'studio', stage: 'sew' },
  { src: '/images/work/ts-131.webp', w: 491, h: 778, alt: "Sewing a black and white print", cat: 'studio', stage: 'sew' },
  { src: '/images/work/ts-01.webp', w: 720, h: 1080, alt: "Fitting session for a white senator", cat: 'studio', stage: 'fit' },
  { src: '/images/work/ts-109.webp', w: 720, h: 1080, alt: "Final fitting with a red fedora", cat: 'studio', stage: 'fit' },
  { src: '/images/work/ts-13.webp', w: 1028, h: 1280, alt: "Two clients in bold prints inside the showroom", cat: 'studio', stage: 'ready' },
  { src: '/images/work/ts-84.webp', w: 608, h: 1080, alt: "Tatiana Stitches branded shopping bags ready for pickup", cat: 'studio', stage: 'ready' },
];

export const byId = (n: number) => {
  const s = `/images/work/ts-${String(n).padStart(2, '0')}.webp`;
  return works.find((x) => x.src === s)!;
};
